# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(351, 356)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(242, 178, 55, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush1 = QBrush(QColor(25, 42, 50, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        MainWindow.setPalette(palette)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lbl_d1 = QLabel(self.centralwidget)
        self.lbl_d1.setObjectName(u"lbl_d1")
        self.lbl_d1.setGeometry(QRect(4, 7, 118, 30))
        font = QFont()
        font.setFamilies([u"Comic Sans MS"])
        font.setPointSize(14)
        self.lbl_d1.setFont(font)
        self.lbl_d1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lbl_d2 = QLabel(self.centralwidget)
        self.lbl_d2.setObjectName(u"lbl_d2")
        self.lbl_d2.setGeometry(QRect(123, 6, 118, 30))
        self.lbl_d2.setFont(font)
        self.lbl_d2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lbl_d3 = QLabel(self.centralwidget)
        self.lbl_d3.setObjectName(u"lbl_d3")
        self.lbl_d3.setGeometry(QRect(240, 6, 118, 30))
        self.lbl_d3.setFont(font)
        self.lbl_d3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lbl_tmp = QLabel(self.centralwidget)
        self.lbl_tmp.setObjectName(u"lbl_tmp")
        self.lbl_tmp.setGeometry(QRect(135, 190, 211, 30))
        self.lbl_tmp.setFont(font)
        self.lbl_tmp.setStyleSheet(u"color: rgb(49, 196, 190);")
        self.lbl_desc = QLabel(self.centralwidget)
        self.lbl_desc.setObjectName(u"lbl_desc")
        self.lbl_desc.setGeometry(QRect(135, 144, 211, 30))
        self.lbl_desc.setFont(font)
        self.lbl_desc.setStyleSheet(u"color: rgb(49, 196, 190);")
        self.lbl_tmp1 = QLabel(self.centralwidget)
        self.lbl_tmp1.setObjectName(u"lbl_tmp1")
        self.lbl_tmp1.setGeometry(QRect(4, 54, 115, 15))
        self.lbl_tmp1.setFont(font)
        self.lbl_tmp1.setStyleSheet(u"color: rgb(242, 178, 55);")
        self.lbl_wind1 = QLabel(self.centralwidget)
        self.lbl_wind1.setObjectName(u"lbl_wind1")
        self.lbl_wind1.setGeometry(QRect(4, 84, 115, 15))
        self.lbl_wind1.setFont(font)
        self.lbl_wind1.setStyleSheet(u"color: rgb(242, 178, 55);")
        self.lbl_tmp2 = QLabel(self.centralwidget)
        self.lbl_tmp2.setObjectName(u"lbl_tmp2")
        self.lbl_tmp2.setGeometry(QRect(123, 54, 115, 15))
        self.lbl_tmp2.setFont(font)
        self.lbl_tmp2.setStyleSheet(u"color: rgb(242, 178, 55);")
        self.lbl_wind2 = QLabel(self.centralwidget)
        self.lbl_wind2.setObjectName(u"lbl_wind2")
        self.lbl_wind2.setGeometry(QRect(123, 84, 115, 15))
        self.lbl_wind2.setFont(font)
        self.lbl_wind2.setStyleSheet(u"color: rgb(242, 178, 55);")
        self.lbl_tmp3 = QLabel(self.centralwidget)
        self.lbl_tmp3.setObjectName(u"lbl_tmp3")
        self.lbl_tmp3.setGeometry(QRect(240, 54, 115, 15))
        self.lbl_tmp3.setFont(font)
        self.lbl_tmp3.setStyleSheet(u"color: rgb(242, 178, 55);")
        self.lbl_wind3 = QLabel(self.centralwidget)
        self.lbl_wind3.setObjectName(u"lbl_wind3")
        self.lbl_wind3.setGeometry(QRect(240, 84, 115, 15))
        self.lbl_wind3.setFont(font)
        self.lbl_wind3.setStyleSheet(u"color: rgb(242, 178, 55);")
        self.lbl_error = QLabel(self.centralwidget)
        self.lbl_error.setObjectName(u"lbl_error")
        self.lbl_error.setGeometry(QRect(10, 240, 331, 40))
        self.lbl_error.setFont(font)
        self.lbl_error.setStyleSheet(u"color: rgb(186, 124, 186);")
        self.lbl_qpix = QLabel(self.centralwidget)
        self.lbl_qpix.setObjectName(u"lbl_qpix")
        self.lbl_qpix.setGeometry(QRect(4, 120, 128, 128))
        self.btn_search = QPushButton(self.centralwidget)
        self.btn_search.setObjectName(u"btn_search")
        self.btn_search.setGeometry(QRect(8, 279, 111, 44))
        font1 = QFont()
        font1.setFamilies([u"Comic Sans MS"])
        font1.setPointSize(10)
        font1.setBold(True)
        self.btn_search.setFont(font1)
        self.btn_search.setStyleSheet(u"QPushButton{\n"
"background-color: rgb(242, 178, 55)\n"
"}")
        self.lbl_wind = QLabel(self.centralwidget)
        self.lbl_wind.setObjectName(u"lbl_wind")
        self.lbl_wind.setGeometry(QRect(135, 222, 211, 30))
        self.lbl_wind.setFont(font)
        self.lbl_wind.setStyleSheet(u"color: rgb(49, 196, 190);")
        self.lne_city = QLineEdit(self.centralwidget)
        self.lne_city.setObjectName(u"lne_city")
        self.lne_city.setGeometry(QRect(122, 280, 222, 40))
        font2 = QFont()
        font2.setFamilies([u"Comic Sans MS"])
        font2.setPointSize(14)
        font2.setBold(True)
        self.lne_city.setFont(font2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Weather", None))
        self.lbl_d1.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.lbl_d2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.lbl_d3.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.lbl_tmp.setText("")
        self.lbl_desc.setText("")
        self.lbl_tmp1.setText("")
        self.lbl_wind1.setText("")
        self.lbl_tmp2.setText("")
        self.lbl_wind2.setText("")
        self.lbl_tmp3.setText("")
        self.lbl_wind3.setText("")
        self.lbl_error.setText("")
        self.lbl_qpix.setText("")
        self.btn_search.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.lbl_wind.setText("")
    # retranslateUi

